### ISSUE TITLE
Please fix your unit tests

### ISSUE THREAD

**Issue by mbi** [pfpayments/python-sdk#1]
None of your tests are currently being run (because the `test_*.py` doesn't match any test files in `test`)

![image](https://user-images.githubusercontent.com/131808/164177257-74e3e267-4ebe-46cf-8b46-68a7d10d973a.png)

... but [still fails](https://app.travis-ci.com/github/pfpayments/python-sdk/branches).

**Comment by theodorspringwallee** [comment]
Dear [mbi](https://github.com/mbi)

Sorry for the late response. We will check this.

**Comment by vttn** [comment]
The tests have been moved to github actions
