### ISSUE TITLE
Wrong installation documentation

### ISSUE THREAD

**Issue by mbi** [pfpayments/python-sdk#2]
Your README mentions the recommended installation method is via pip, but PyPI [doesn't have any published versions](https://pypi.org/search/?q=postfinancecheckout), looks like the package was never published.

```bash
 ~ ❯ python3.8 -m pip install postfinancecheckout
ERROR: Could not find a version that satisfies the requirement postfinancecheckout (from versions: none)
ERROR: No matching distribution found for postfinancecheckout
```

**Comment by theodorspringwallee** [comment]
Dear [mbi](https://github.com/mbi)

You were right. But since June we have releases there: https://pypi.org/project/postfinancecheckout/#history

Feel free to use them.

![image](https://user-images.githubusercontent.com/85299706/193781564-702ebd7a-e88f-4350-8f95-0564a062a1c7.png)
